/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteRouteImport } from './routes/favorites.route'
import { Route as CheckoutRouteRouteImport } from './routes/checkout.route'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as ProductIdRouteRouteImport } from './routes/product.$id.route'

const FavoritesRouteRoute = FavoritesRouteRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRouteRoute = ProductIdRouteRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/favorites': typeof FavoritesRouteRoute
  '/product/$id': typeof ProductIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/favorites': typeof FavoritesRouteRoute
  '/product/$id': typeof ProductIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/favorites': typeof FavoritesRouteRoute
  '/product/$id': typeof ProductIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/favorites' | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/favorites' | '/product/$id'
  id: '__root__' | '/' | '/checkout' | '/favorites' | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  CheckoutRouteRoute: typeof CheckoutRouteRoute
  FavoritesRouteRoute: typeof FavoritesRouteRoute
  ProductIdRouteRoute: typeof ProductIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  CheckoutRouteRoute: CheckoutRouteRoute,
  FavoritesRouteRoute: FavoritesRouteRoute,
  ProductIdRouteRoute: ProductIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
